# Site
name: "Devkimson"
title: "Devkimson"
description: "나를 표현하는 블로그. 끊임없이 도전하고 공부하는 예비 개발자입니다."
logo: 'assets/images/logo-k-color.png'
favicon: 'assets/images/logo-k-color.png'
url: "http://kkn1125.github.io"
baseurl: ""
# baseurl은 github 저장소 명으로 바꿔줘야함
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Kimson:
    name: Kyeongnam
    display_name: Kimson
    profile: assets/images/kim.jpg
    avatar: assets/images/logo-k-mono.png
    gravatar: assets/images/logo-k-mono.png
    email: chaplet01@gmail.com
    web: https://kkn1125.github.io
    twitter: https://twitter.com/wowthemesnet
    description: "하루하루 게을리하지 않고 나만의 방식으로 발전해나가는 예비 개발자입니다"
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
